repos:
- repo: https://github.com/jumanjihouse/pre-commit-hooks
  rev: 3.0.0  # or specific git tag
  hooks:
    - id: script-must-have-extension
    - id: script-must-not-have-extension
    - id: shellcheck
-   repo: https://github.com/sqlfluff/sqlfluff
    rev: 0.9.1
    hooks:
    -   id: sqlfluff-lint
