# Create ephemeral runtime directories for Pioreactor
# d <path> <mode> <user> <group> <age> <argument>

d /run/pioreactor 0755 pioreactor www-data - -
d /run/pioreactor/exports 2775 pioreactor www-data - -
d /run/pioreactor/cache 2770 pioreactor www-data - -
f /run/pioreactor/cache/local_intermittent_pioreactor_metadata.sqlite 0660 pioreactor www-data - -
f /run/pioreactor/cache/huey.db 0660 pioreactor www-data - -
